using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.ResourceManagement;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    public Button CharacterSetupButton => CharacterSetup;

    /// <summary>The dotted run between the name and its tag; CmuLobbyLook gives it its stylebox.</summary>
    public PanelContainer HeadLeaderPanel => HeadLeader;
    public Button PrevCharacterButton => PrevCharButton;
    public Button NextCharacterButton => NextCharButton;
    public Button IgnoreAllegianceToggle => IgnoreAllegianceButton;

    private EntityUid? _previewDummy;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // The CRT theme styles every button label at one size via a stylesheet rule. FontOverride
        // is the reliable way to make just this one bigger - another style class would tie with
        // that rule on specificity.
        if (StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.Label.FontOverride = StyleNano.GetCrtFont(_resourceCache, 10);

        // Base menu only: toggled on turns the button solid red. The default Pressed state for a
        // plain Button is a thin highlighted border, easy to miss at a glance for something that
        // changes spawn behaviour. The CRT theme already themes every button consistently through
        // CrtButton, so this is left alone there.
        if (!StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.AddStyleClass(StyleNano.StyleClassButtonToggleRed);

        // Colour alone is never a safe state indicator - readable differently depending on vision,
        // and on the CRT theme specifically the accent is player-configurable, so "red" can't be
        // assumed to contrast with it. The label states on/off directly instead.
        UpdateIgnoreAllegianceText(IgnoreAllegianceButton.Pressed);
        IgnoreAllegianceButton.OnToggled += args => UpdateIgnoreAllegianceText(args.Pressed);
    }

    private void UpdateIgnoreAllegianceText(bool pressed)
    {
        IgnoreAllegianceButton.Text = Loc.GetString(pressed
            ? "lobby-character-preview-ignore-allegiance-on"
            : "lobby-character-preview-ignore-allegiance-off");
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;

        HeadRow.Visible = value;
        HeadRule.Visible = value;
    }

    /// <summary>
    ///     Sets the page's head: the character's name as the big fact, and their pronoun and age as
    ///     the tag beside it. The name is plain text because it is one value at heading size; the tag
    ///     stays markup so the pronoun and the age keep their own colours.
    /// </summary>
    public void SetSummaryText(string name, string ageMarkup)
    {
        SummaryName.Text = name;
        SetSummaryLine(SummaryAge, ageMarkup);
    }

    private static void SetSummaryLine(RichTextLabel label, string markup)
    {
        if (string.IsNullOrWhiteSpace(markup))
        {
            label.SetMessage(FormattedMessage.Empty);
            label.Visible = false;
            return;
        }

        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markup));
        label.Visible = true;
    }

    public void SetJobText(string value)
    {
        JobSummary.Text = value;
        JobSummary.Visible = !string.IsNullOrWhiteSpace(value);
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            // Down from 4x/112. The sprite was the tallest thing in the block and set its height,
            // which is the height the stats column beside it has to match; smaller here buys the row
            // back the vertical space without costing legibility on a 32px source sprite.
            Scale = new Vector2(3f, 3f),
            MaxSize = new Vector2(84, 84),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    [System.Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;
    }
}
